### PR TITLE
Turn off GCC to treat warnings as errors

### PR DESCRIPTION
**Pull request by Flowertome**
Incoming flags -Wno-address-of-packed-member

Signed-off-by: 弱弱的胖橘猫丷 <gesangtome@foxmail.com>

### CODE REVIEW

**Comment by anestisb** [comment]
@Flowertome which gcc version caused issue with the above? Want to double check the code and see if warning is actual a false positive.

**Comment by Flowertome** [comment]
@anestisb 
My gcc version is 9.2.1

**Comment by anestisb** [comment]
Resolved issue with https://github.com/anestisb/vdexExtractor/commit/9990fa00a59639a81d0d2af7e6cd5621f9df1eba. Disabling the matching warning type is no longer needed. Can you please check that is also works in your environment?

**Comment by Flowertome** [comment]
@anestisb Tested problem has been solved, thank you for your answer

**Pull request closed without merging**
